### ISSUE TITLE
UnsupportedOperationException from JPEGTweaker.insertExif

### ISSUE THREAD

**Issue by dspurling** [dragon66/icafe#20]
I am getting this exception when call insertExif from JPEGTweaker

java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableMap.put(Unknown Source)
	at com.icafe4j.image.tiff.IFD.addChild(Unknown Source)
	at com.icafe4j.image.jpeg.JPEGTweaker.insertExif(Unknown Source)
	at arpm.image.ImageAdjuster.addMetadata(ImageAdjuster.java:215)
	at arpm.image.ImageAdjuster.main(ImageAdjuster.java:363)

**Comment by dragon66** [comment]
Hi @dspurling:

This is a bug. I have fixed it. Check the latest build.
