### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by dragon66** [dragon66/icafe#74]
hi dragon66. i need help. where i can write question? here? i ask here yet. 
 first my exception and after code
```

Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.icafe4j.image.meta.Metadata.<clinit>(Unknown Source)
	at vectorcleaner.Metadata1.populateExif(Metadata1.java:41)
	at vectorcleaner.Metadata1.main(Metadata1.java:127)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
C:\Users\rajab\AppData\Local\NetBeans\Cache\8.2\executor-snippets\run.xml:53: Java returned: 1
```
`BUILD FAILED (total time: 0 seconds)`

```
  
  private static List<IPTCDataSet> createIPTCDataSet() {
  	List<IPTCDataSet> iptcs = new ArrayList<IPTCDataSet>();
  	iptcs.add(new IPTCDataSet(IPTCApplicationTag.COPYRIGHT_NOTICE, "Copyright 2014-2016, yuwen_66@yahoo.com"));
  	iptcs.add(new IPTCDataSet(IPTCApplicationTag.CATEGORY, "ICAFE"));
  	iptcs.add(new IPTCDataSet(IPTCApplicationTag.KEY_WORDS, "Welcome 'icafe' user!"));
  	
  	return iptcs;
  }

  private static IPTC createIPTC() {
  	IPTC iptc = new IPTC();
  	iptc.addDataSets(createIPTCDataSet());
  	return iptc;
  }

public static void main(String[] args) throws  IOException {
  FileInputStream fin = new FileInputStream("C:/Users/rajab/Desktop/test/ibo.jpeg");
  FileOutputStream fout = new FileOutputStream("C:/Users/rajab/Desktop/test/ibo/ibo.jpeg");

  List<Metadata> metaList = new ArrayList<Metadata>();
  metaList.add(populateExif(TiffExif.class));
  metaList.add(createIPTC());
  metaList.add(new Comments(Arrays.asList("Comment1", "Comment2")));
  
  Metadata.insertMetadata(metaList, fin, fout);
}
}
```

**Comment by dragon66** [comment]
@ibrahimrajabl when you do the build please include the jars in the lib folder. This will fix the issue.

Wen

**Comment by AndriiLaktionov** [comment]
I am trying to change the meta data of an image in android. I'm using the icafe library.
I used the following code.

            FileInputStream fin = null;
            try {
                fin = new FileInputStream(imgUri);
            } catch (IOException e) {
                e.printStackTrace();
            }
            FileOutputStream fout = null;
            try {
                fout = new FileOutputStream("/storage/emulated/0/DCIM/IMG_0615-0001.jpg");
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            }

            try {
                Metadata.insertIPTC(fin, fout, createIPTCDataSet(), true);
            } catch (IOException e) {
                e.printStackTrace();
            }

But I got the following error.

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: info.ermi.hiddennotes, PID: 11664
    java.lang.RuntimeException: Error while reading bytes into buffer
        at com.icafe4j.io.PeekHeadInputStream.<init>(Unknown Source)
        at com.icafe4j.image.meta.Metadata.insertIPTC(Unknown Source)
        at info.ermi.hiddennotes.Activity.NoteActivity.lambda$onCreate$2$NoteActivity(NoteActivity.java:118)
        at info.ermi.hiddennotes.Activity.-$$Lambda$NoteActivity$VFZ6sQOwqftFB0X_enm3Ph1dZq4.onClick(lambda)
        at android.view.View.performClick(View.java:6261)
        at android.view.View$PerformClick.run(View.java:23748)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

Can you help me?

**Comment by dragon66** [comment]
@AndriiLaktionov most probably your input imgUrl contains no or less number of bytes required by the PeekHeadInputStream.

**Comment by AndriiLaktionov** [comment]
@dragon66 
thanks for your reply.
Do you have android example to implement icafe?

**Comment by dragon66** [comment]
@AndriiLaktionov I am not an expert in Android. I do have a testing Android repository to test Android version of icafe: https://github.com/dragon66/MyAndroidApp

**Comment by AndriiLaktionov** [comment]
Thanks
